2025-09-16 00:30:39,672 - ERROR - Error al verificar estado de backups: The current Flask app is not registered with this 'SQLAlchemy' instance. Did you forget to call 'init_app', or did you create multiple 'SQLAlchemy' instances?
2025-09-16 00:30:48,605 - ERROR - Error al crear backup automático: The current Flask app is not registered with this 'SQLAlchemy' instance. Did you forget to call 'init_app', or did you create multiple 'SQLAlchemy' instances?
2025-09-16 00:31:05,069 - INFO - Backup creado: backups/backup_auto_20250916_003105.db
2025-09-16 00:31:05,071 - INFO - Backup automático completado: backup_auto_20250916_003105.db (61440 bytes)
